import { PDFDocument, StandardFonts, rgb } from 'pdf-lib/dist/pdf-lib.esm.js';
import * as XLSX from 'xlsx';
import { MockDatabaseSnapshot, getProduct, getProductVariant } from './mockDatabase';

export type ReportType = 'sales' | 'orders' | 'trip_profit' | 'purchases' | 'expenses' | 'customer_payments' | 'inventory';
export type ReportRow = Record<string, string | number>;
const title = (type: ReportType) => type.replace('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const money = (value: number) => Number(value.toFixed(2));
const inRange = (value: string, from: string, to: string) => value.slice(0, 10) >= from && value.slice(0, 10) <= to;
const fileName = (type: ReportType, from: string, to: string, extension: string) => `OpsPS_${title(type).replace(/ /g, '')}_${from}_to_${to}.${extension}`;
const download = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
function context(db: MockDatabaseSnapshot, orderId: string) { const order = db.orders.find((entry) => entry.id === orderId); const item = db.orderItems.find((entry) => entry.orderId === orderId); const variant = item ? getProductVariant(item.productVariantId, db) : undefined; const product = variant ? getProduct(variant.productId, db) : undefined; const trip = order ? db.trips.find((entry) => entry.id === order.tripId) : undefined; return { order, item, variant, product, trip }; }
function purchases(db: MockDatabaseSnapshot, from: string, to: string): ReportRow[] { const rows: ReportRow[] = []; db.orders.filter((order) => order.purchase?.confirmedAt && inRange(order.purchase.confirmedAt, from, to)).forEach((order) => { const { item, variant, product, trip } = context(db, order.id); const purchase = order.purchase!; rows.push({ 'Purchase ID': order.purchaseId ?? '', Date: purchase.confirmedAt!.slice(0, 10), Trip: trip?.name ?? order.tripId, 'Order ID': order.id, Customer: order.customerName, Product: product?.name ?? '', Size: variant?.size ?? '', 'Purchase Classification': 'Customer Order', Quantity: item?.quantity ?? 0, 'Product Cost': purchase.productCost, Transport: purchase.transport, Parking: purchase.parking, Toll: purchase.toll, 'Other Expenses': purchase.other, 'Total Purchase': purchase.productCost + purchase.transport + purchase.parking + purchase.toll + purchase.other, 'Payment Method': purchase.paymentMethod ?? '', Receipt: purchase.receiptUri ? 'Attached' : 'None', 'Purchase Status': 'Confirmed' }); }); db.extraStockPurchases.filter((purchase) => inRange(purchase.purchaseDate, from, to)).forEach((purchase) => { const product = getProduct(purchase.productId, db); const variant = getProductVariant(purchase.productVariantId, db); const trip = db.trips.find((entry) => entry.id === purchase.tripId); rows.push({ 'Purchase ID': purchase.id, Date: purchase.purchaseDate.slice(0, 10), Trip: trip?.name ?? purchase.tripId, 'Order ID': '', Customer: '', Product: product?.name ?? '', Size: variant?.size ?? '', 'Purchase Classification': 'Extra Stock', Quantity: purchase.quantity, 'Product Cost': purchase.cost, Transport: 0, Parking: 0, Toll: 0, 'Other Expenses': 0, 'Total Purchase': purchase.cost, 'Payment Method': '', Receipt: purchase.purchaseReceiptUri ? 'Attached' : 'None', 'Purchase Status': 'Confirmed' }); }); return rows; }

export function buildReport(type: ReportType, db: MockDatabaseSnapshot, from: string, to: string) {
  let rows: ReportRow[] = [];
  if (type === 'sales' || type === 'orders' || type === 'customer_payments') { db.orders.filter((order) => inRange(order.orderDate, from, to) && (type !== 'sales' || order.status !== 'cancelled')).forEach((order) => { const { item, variant, product, trip } = context(db, order.id); if (type === 'customer_payments') { if (order.paymentReceipt?.verified) rows.push({ 'Payment Date': order.paymentReceipt.date.slice(0, 10), 'Order ID': order.id, Customer: order.customerName, Trip: trip?.name ?? order.tripId, Amount: order.paymentReceipt.amount, 'Payment Mode': order.paymentMode ?? '', 'Payment Status': order.paymentStatus, Receipt: order.paymentReceipt.receiptUri ? 'Attached' : 'None', 'Verified Date': order.paymentVerifiedAt?.slice(0, 10) ?? '' }); return; } const base = { Date: order.orderDate.slice(0, 10), 'Order ID': order.id, Customer: order.customerName, Phone: order.customerPhone ?? '', Trip: trip?.name ?? order.tripId, Product: product?.name ?? '', Size: variant?.size ?? '', Quantity: item?.quantity ?? 0, 'Selling Price': product?.sellingPrice ?? 0, 'Shipping Fee': order.shippingFee, 'Total Sales': order.total, 'Payment Mode': order.paymentMode ?? '', 'Payment Status': order.paymentStatus, Availability: order.availabilityStatus ?? '', 'Order Status': order.status, 'Tracking Number': order.shipment?.trackingNumber ?? '' }; rows.push(type === 'sales' ? base : { 'Order ID': base['Order ID'], 'Order Date': base.Date, Customer: base.Customer, Phone: base.Phone, Trip: base.Trip, Product: base.Product, Size: base.Size, Quantity: base.Quantity, Amount: base['Total Sales'], 'Payment Mode': base['Payment Mode'], 'Payment Status': base['Payment Status'], Availability: base.Availability, 'Order Status': base['Order Status'], 'Tracking Number': base['Tracking Number'] }); }); }
  else if (type === 'purchases') rows = purchases(db, from, to);
  else if (type === 'expenses') rows = db.financeTransactions.filter((entry) => entry.type === 'expense' && inRange(entry.date, from, to)).map((entry) => ({ Date: entry.date.slice(0, 10), Description: entry.description, Category: entry.category, 'Payment Method': entry.paymentMethod, Amount: entry.amount, Trip: db.trips.find((trip) => trip.id === entry.tripId)?.name ?? entry.tripId ?? '', Order: entry.orderId ?? '', Purchase: entry.purchaseId ?? '', Reference: entry.referenceId ?? '' }));
  else if (type === 'inventory') rows = db.products.flatMap((product) => db.productVariants.filter((variant) => variant.productId === product.id).map((variant) => ({ Product: product.name, Category: product.category, Trip: db.trips.find((trip) => trip.id === product.tripId)?.name ?? product.tripId, Size: variant.size, Stock: variant.stock, 'Cost Price': product.costPrice, 'Selling Price': product.sellingPrice, 'Stock Value': money(variant.stock * product.costPrice), Status: variant.stock === 0 ? 'Out of Stock' : variant.stock <= 5 ? 'Low Stock' : 'In Stock' })));
  else rows = db.trips.filter((trip) => inRange(trip.tripDate, from, to)).map((trip) => { const tripOrders = db.orders.filter((order) => order.tripId === trip.id && order.status !== 'cancelled'); const tripPurchases = purchases(db, from, to).filter((row) => row.Trip === trip.name); const sales = tripOrders.reduce((sum, order) => sum + order.total, 0); const productCost = tripPurchases.reduce((sum, row) => sum + Number(row['Product Cost']), 0); const expenses = db.financeTransactions.filter((entry) => entry.type === 'expense' && entry.tripId === trip.id && !entry.purchaseId && inRange(entry.date, from, to)).reduce((sum, entry) => sum + entry.amount, 0); const transport = tripPurchases.reduce((sum, row) => sum + Number(row.Transport), 0); const parking = tripPurchases.reduce((sum, row) => sum + Number(row.Parking), 0); const toll = tripPurchases.reduce((sum, row) => sum + Number(row.Toll), 0); const other = tripPurchases.reduce((sum, row) => sum + Number(row['Other Expenses']), 0) + expenses; return { Trip: trip.name, Destination: trip.destination, 'Trip Date': trip.tripDate, Sales: money(sales), 'Product Cost': money(productCost), Transport: money(transport), Parking: money(parking), Toll: money(toll), 'Other Expenses': money(other), 'Net Profit': money(sales - productCost - transport - parking - toll - other) }; });
  const summary: ReportRow = { Rows: rows.length }; if (type === 'sales') { summary['Total Sales'] = money(rows.reduce((sum, row) => sum + Number(row['Total Sales']), 0)); summary['Total Orders'] = new Set(rows.map((row) => row['Order ID'])).size; summary['Total Items'] = rows.reduce((sum, row) => sum + Number(row.Quantity), 0); summary['Outstanding Payment'] = money(rows.filter((row) => row['Payment Status'] !== 'paid').reduce((sum, row) => sum + Number(row['Total Sales']), 0)); } if (type === 'expenses') { summary['Total Expenses'] = money(rows.reduce((sum, row) => sum + Number(row.Amount), 0)); summary.Bank = money(rows.filter((row) => row['Payment Method'] === 'bank').reduce((sum, row) => sum + Number(row.Amount), 0)); summary.Cash = money(rows.filter((row) => row['Payment Method'] === 'cash').reduce((sum, row) => sum + Number(row.Amount), 0)); } if (type === 'purchases') { summary['Total Purchases'] = money(rows.reduce((sum, row) => sum + Number(row['Total Purchase']), 0)); summary['Customer Orders'] = rows.filter((row) => row['Purchase Classification'] === 'Customer Order').length; summary['Extra Stock'] = rows.filter((row) => row['Purchase Classification'] === 'Extra Stock').length; } if (type === 'inventory') { summary['Total Products'] = new Set(rows.map((row) => row.Product)).size; summary['Total Units'] = rows.reduce((sum, row) => sum + Number(row.Stock), 0); summary['Stock Value'] = money(rows.reduce((sum, row) => sum + Number(row['Stock Value']), 0)); } if (type === 'customer_payments') summary['Received Cash'] = money(rows.reduce((sum, row) => sum + Number(row.Amount), 0)); if (type === 'trip_profit') { summary.Sales = money(rows.reduce((sum, row) => sum + Number(row.Sales), 0)); summary['Total Cost'] = money(rows.reduce((sum, row) => sum + Number(row['Product Cost']) + Number(row.Transport) + Number(row.Parking) + Number(row.Toll) + Number(row['Other Expenses']), 0)); summary['Net Profit'] = money(rows.reduce((sum, row) => sum + Number(row['Net Profit']), 0)); } return { rows, summary };
}
export function exportExcel(type: ReportType, result: { rows: ReportRow[]; summary: ReportRow }, from: string, to: string) { const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet([result.summary]), `${title(type)} Summary`); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(result.rows), `${title(type)} Details`); const output = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' }); download(new Blob([output], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), fileName(type, from, to, 'xlsx')); }
export async function exportPdf(type: ReportType, result: { rows: ReportRow[]; summary: ReportRow }, from: string, to: string) { const pdf = await PDFDocument.create(); let page = pdf.addPage([842, 595]); const font = await pdf.embedFont(StandardFonts.Helvetica); let y = 560; const write = (text: string, size = 10) => { page.drawText(text.slice(0, 130), { x: 28, y, size, font, color: rgb(0.12, 0.16, 0.22) }); y -= size + 8; if (y < 30) { page = pdf.addPage([842, 595]); y = 560; } }; write(`OpsPS - ${title(type)} Report`, 18); write(`Date Range: ${from} to ${to}`); write(`Generated: ${new Date().toISOString().slice(0, 10)}`); write(`Summary: ${Object.entries(result.summary).map(([key, value]) => `${key}: ${value}`).join(' | ')}`); result.rows.forEach((row) => write(Object.entries(row).map(([key, value]) => `${key}: ${value}`).join(' | '), 7)); const bytes = await pdf.save(); download(new Blob([bytes.buffer as ArrayBuffer], { type: 'application/pdf' }), fileName(type, from, to, 'pdf')); }
