import React from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useMockDatabase } from '../../services/mockDatabase';
import { BORDER_RADIUS, FONT_SIZES, SPACING, THEME } from '../../theme';

export default function OrdersScreen() {
  const db = useMockDatabase();
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Orders</Text><Text style={styles.subtitle}>Review customer requests and fulfilment status.</Text>{db.orders.map((order) => { const orderItem = db.orderItems.find((item) => item.orderId === order.id); const variant = orderItem ? db.productVariants.find((item) => item.id === orderItem.productVariantId) : undefined; const product = variant ? db.products.find((item) => item.id === variant.productId) : undefined; const trip = db.trips.find((item) => item.id === order.tripId); return <Pressable key={order.id} style={styles.card} onPress={() => router.push(`/order/${order.id}`)}><View style={styles.row}><View style={styles.info}><Text style={styles.order}>{order.id}</Text><Text style={styles.customer}>{order.customerName}</Text><Text style={styles.meta}>{product?.name ?? 'Product'} · {trip?.name ?? 'Trip'}</Text></View><View><Text style={styles.amount}>RM{order.total.toFixed(2)}</Text><Text style={styles.status}>{order.availabilityStatus === 'confirmed' ? 'Availability Confirmed' : order.status === 'cancelled' ? 'Cancelled' : 'Availability Pending'}</Text></View></View></Pressable>; })}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: THEME.background }, content: { padding: SPACING['2xl'], paddingBottom: SPACING['3xl'] }, title: { color: THEME.text.primary, fontSize: FONT_SIZES['2xl'], fontWeight: '800' }, subtitle: { color: THEME.text.secondary, marginTop: SPACING.xs, marginBottom: SPACING.lg }, card: { backgroundColor: THEME.surface, borderRadius: BORDER_RADIUS.lg, borderWidth: 1, borderColor: THEME.border, padding: SPACING.lg, marginBottom: SPACING.md }, row: { flexDirection: 'row', justifyContent: 'space-between' }, info: { flex: 1 }, order: { color: THEME.primary, fontWeight: '800' }, customer: { color: THEME.text.primary, fontSize: FONT_SIZES.base, fontWeight: '700', marginTop: SPACING.xs }, meta: { color: THEME.text.secondary, fontSize: FONT_SIZES.sm, marginTop: SPACING.xs }, amount: { color: THEME.text.primary, fontWeight: '800', textAlign: 'right' }, status: { color: THEME.text.secondary, fontSize: FONT_SIZES.xs, marginTop: SPACING.xs, textAlign: 'right' } });
