import React, { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { buildReport, exportExcel, exportPdf, ReportType } from '../../services/reporting';
import { useMockDatabase } from '../../services/mockDatabase';
import { BORDER_RADIUS, FONT_SIZES, SPACING, THEME } from '../../theme';

const types: ReportType[] = ['sales', 'orders', 'trip_profit', 'purchases', 'expenses', 'customer_payments', 'inventory'];
const labels: Record<ReportType, string> = { sales: 'Sales', orders: 'Orders', trip_profit: 'Trip Profit', purchases: 'Purchases', expenses: 'Expenses', customer_payments: 'Customer Payments', inventory: 'Inventory' };
function monthRange() { const now = new Date(); const from = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10); return { from, to: now.toISOString().slice(0, 10) }; }
export default function ReportsScreen() {
  const db = useMockDatabase();
  const defaults = monthRange();
  const [type, setType] = useState<ReportType>('sales');
  const [from, setFrom] = useState(defaults.from);
  const [to, setTo] = useState(defaults.to);
  const [result, setResult] = useState(() => buildReport('sales', db, defaults.from, defaults.to));
  const generate = () => setResult(buildReport(type, db, from, to));
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Reports</Text><Text style={styles.subtitle}>Generated from the current OpsPS database.</Text><View style={styles.card}><Text style={styles.label}>Date From</Text><TextInput value={from} onChangeText={setFrom} placeholder="YYYY-MM-DD" style={styles.input} /><Text style={styles.label}>Date To</Text><TextInput value={to} onChangeText={setTo} placeholder="YYYY-MM-DD" style={styles.input} /><Text style={styles.label}>Report Type</Text><View style={styles.actions}>{types.map((entry) => <Pressable key={entry} style={[styles.option, type === entry && styles.selected]} onPress={() => setType(entry)}><Text style={styles.optionText}>{labels[entry]}</Text></Pressable>)}</View><Pressable style={styles.primary} onPress={generate}><Text style={styles.primaryText}>Generate Report</Text></Pressable></View><View style={styles.summary}><Text style={styles.sectionTitle}>{labels[type]} Summary</Text>{Object.entries(result.summary).map(([key, value]) => <View key={key} style={styles.summaryRow}><Text style={styles.label}>{key}</Text><Text style={styles.value}>{value}</Text></View>)}</View><View style={styles.actions}><Pressable style={styles.export} onPress={() => exportPdf(type, result, from, to)}><Text style={styles.exportText}>Download PDF</Text></Pressable><Pressable style={styles.export} onPress={() => exportExcel(type, result, from, to)}><Text style={styles.exportText}>Download Excel</Text></Pressable></View><Text style={styles.sectionTitle}>Report Data ({result.rows.length})</Text>{result.rows.map((row, index) => <View key={index} style={styles.row}>{Object.entries(row).map(([key, value]) => <Text key={key} style={styles.cell}>{key}: {value}</Text>)}</View>)}{!result.rows.length && <Text style={styles.empty}>No records in this date range.</Text>}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: THEME.background }, content: { width: '100%', maxWidth: 900, alignSelf: 'center', padding: SPACING['2xl'], paddingBottom: SPACING['3xl'] }, title: { color: THEME.text.primary, fontSize: FONT_SIZES['2xl'], fontWeight: '800' }, subtitle: { color: THEME.text.secondary, marginVertical: SPACING.md }, card: { backgroundColor: THEME.surface, borderWidth: 1, borderColor: THEME.border, borderRadius: BORDER_RADIUS.md, padding: SPACING.lg, marginBottom: SPACING.md }, label: { color: THEME.text.primary, fontWeight: '700' }, input: { borderWidth: 1, borderColor: THEME.border, borderRadius: BORDER_RADIUS.md, padding: SPACING.md, marginVertical: SPACING.xs, marginBottom: SPACING.md, color: THEME.text.primary }, actions: { flexDirection: 'row', gap: SPACING.sm, flexWrap: 'wrap', marginTop: SPACING.sm }, option: { backgroundColor: '#F5F3FF', borderRadius: BORDER_RADIUS.md, padding: SPACING.sm }, selected: { borderWidth: 2, borderColor: THEME.primary }, optionText: { color: THEME.primary, fontWeight: '800', fontSize: FONT_SIZES.xs }, primary: { backgroundColor: THEME.primary, borderRadius: BORDER_RADIUS.md, padding: SPACING.md, alignItems: 'center', marginTop: SPACING.md }, primaryText: { color: '#FFFFFF', fontWeight: '800' }, summary: { backgroundColor: THEME.surface, borderRadius: BORDER_RADIUS.md, padding: SPACING.lg, marginBottom: SPACING.md }, sectionTitle: { color: THEME.text.primary, fontSize: FONT_SIZES.lg, fontWeight: '800', marginBottom: SPACING.md }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: SPACING.xs }, value: { color: THEME.primary, fontWeight: '800' }, export: { flex: 1, backgroundColor: THEME.status.success, borderRadius: BORDER_RADIUS.md, padding: SPACING.md, alignItems: 'center' }, exportText: { color: '#FFFFFF', fontWeight: '800' }, row: { backgroundColor: THEME.surface, borderWidth: 1, borderColor: THEME.border, borderRadius: BORDER_RADIUS.sm, padding: SPACING.md, marginBottom: SPACING.sm }, cell: { color: THEME.text.secondary, fontSize: FONT_SIZES.xs, marginBottom: 2 }, empty: { color: THEME.text.secondary, padding: SPACING.lg } });
