import React, { useState } from 'react';
import { Alert, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { ArrowLeft } from 'lucide-react-native';
import { confirmOrderAvailability, createMockShipment, getOrder, getProduct, getProductVariant, isPaymentConfigured, markOrderShipped, rejectPayment, setOrderPaymentMode, syncShipmentStatus, uploadPaymentReceipt, useMockDatabase, verifyPayment } from '../../../services/mockDatabase';
import { BORDER_RADIUS, FONT_SIZES, SPACING, THEME } from '../../../theme';

export default function OrderDetailScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>();
  const db = useMockDatabase();
  const order = id ? getOrder(id, db) : undefined;
  const item = order ? db.orderItems.find((entry) => entry.orderId === order.id) : undefined;
  const variant = item ? getProductVariant(item.productVariantId, db) : undefined;
  const product = variant ? getProduct(variant.productId, db) : undefined;
  const [receipt, setReceipt] = useState(order?.paymentReceipt?.receiptUri ?? '');
  const [customer, setCustomer] = useState(order?.customerName ?? '');

  if (!order || !product) return <SafeAreaView style={styles.safe}><Text style={styles.error}>Order not found.</Text></SafeAreaView>;

  const pickReceipt = async (camera: boolean) => {
    const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) return;
    const result = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.9 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.9 });
    if (!result.canceled) { const uri = result.assets[0].uri; setReceipt(uri); uploadPaymentReceipt(order.id, uri, order.total); }
  };

  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
    <Pressable style={styles.back} onPress={() => router.back()}><ArrowLeft size={18} color={THEME.primary} /><Text style={styles.backText}>Orders</Text></Pressable>
    <Text style={styles.title}>{order.id}</Text>
    <View style={styles.card}><Image source={{ uri: product.image }} style={styles.image} resizeMode="contain" /><Text style={styles.productName}>{product.name}</Text><Text style={styles.meta}>Selling Price: RM{product.sellingPrice.toFixed(2)}</Text><Text style={styles.meta}>Size: {variant?.size ?? 'Standard'} · Quantity: {item?.quantity ?? 0}</Text><Text style={styles.meta}>Trip: {db.trips.find((trip) => trip.id === order.tripId)?.name ?? order.tripId}</Text><Text style={styles.total}>Total: RM{order.total.toFixed(2)}</Text></View>
    <View style={styles.card}><Text style={styles.section}>Customer</Text><Text style={styles.meta}>{order.customerName}</Text><Text style={styles.meta}>{order.customerPhone ?? 'Phone not provided'}</Text><Text style={styles.meta}>{order.deliveryAddress ?? 'Address not provided'}</Text></View>
    <View style={styles.card}><Text style={styles.section}>Availability</Text><Text style={styles.status}>{order.availabilityStatus === 'not_available' ? 'Not Available / Cancelled' : `${order.availabilityStatus ?? 'pending'} · ${order.paymentStatus}`}</Text>{(!order.availabilityStatus || order.availabilityStatus === 'pending') && <View style={styles.actions}><Pressable style={styles.primary} onPress={() => confirmOrderAvailability(order.id, true)}><Text style={styles.primaryText}>Confirm Availability</Text></Pressable><Pressable style={styles.danger} onPress={() => confirmOrderAvailability(order.id, false)}><Text style={styles.dangerText}>Not Available / Cancel</Text></Pressable></View>}</View>
    {order.availabilityStatus === 'confirmed' && !order.paymentMode && <View style={styles.card}><Text style={styles.section}>Payment / Purchase Mode</Text><Pressable style={styles.primary} onPress={() => setOrderPaymentMode(order.id, 'customer_pays_first')}><Text style={styles.primaryText}>Customer Pay First</Text></Pressable><Text style={styles.label}>Customer responsible for later payment</Text><View style={styles.customerRow}>{db.orders.filter((entry) => entry.customerName).map((entry) => <Pressable key={entry.id} style={[styles.option, customer === entry.customerName && styles.selected]} onPress={() => setCustomer(entry.customerName)}><Text style={styles.optionText}>{entry.customerName}</Text></Pressable>)}</View><Pressable style={styles.secondary} onPress={() => customer.trim() && setOrderPaymentMode(order.id, 'ps_buy_first_pay_later', customer.trim())}><Text style={styles.secondaryText}>Confirm Buy Now, Pay Later</Text></Pressable></View>}
    {order.paymentMode === 'customer_pays_first' && <View style={styles.card}><Text style={styles.section}>Payment Required</Text><Text style={styles.instructions}>{isPaymentConfigured(db.paymentSettings) ? `Bank: ${db.paymentSettings.bankName}\nAccount Name: ${db.paymentSettings.accountName}\nAccount Number: ${db.paymentSettings.accountNumber}\nReference: ${db.paymentSettings.paymentReference} ${order.id}\nAmount: RM${order.total.toFixed(2)}` : 'Payment details are not configured yet.'}</Text>{receipt && <Image source={{ uri: receipt }} style={styles.receipt} resizeMode="contain" />}<View style={styles.actions}><Pressable style={styles.secondary} onPress={() => pickReceipt(false)}><Text style={styles.secondaryText}>{receipt ? 'Replace Receipt' : 'Upload Payment Receipt'}</Text></Pressable><Pressable style={styles.secondary} onPress={() => pickReceipt(true)}><Text style={styles.secondaryText}>Camera</Text></Pressable></View>{order.paymentReceipt?.verified === false && <View style={styles.actions}><Pressable style={styles.primary} onPress={() => verifyPayment(order.id)}><Text style={styles.primaryText}>Verify Payment</Text></Pressable><Pressable style={styles.danger} onPress={() => { rejectPayment(order.id); setReceipt(''); Alert.alert('Payment Rejected', 'Payment returned to pending.'); }}><Text style={styles.dangerText}>Reject Payment</Text></Pressable></View>}{order.paymentStatus === 'paid' && <Text style={styles.success}>Payment verified. Purchase may proceed.</Text>}</View>}
    {order.paymentMode === 'ps_buy_first_pay_later' && <View style={styles.card}><Text style={styles.section}>Buy Now, Pay Later</Text><Text style={styles.instructions}>Customer: {order.payLaterCustomerId ?? order.customerName}\nCustomer payment is outstanding. No Money In is recorded until verified.</Text></View>}
    {((order.paymentMode === 'ps_buy_first_pay_later') || (order.paymentMode === 'customer_pays_first' && order.paymentStatus === 'paid')) && !order.purchase && <Pressable style={styles.primary} onPress={() => router.push(`/order/${order.id}/purchase`)}><Text style={styles.primaryText}>Open Purchase Form</Text></Pressable>}
    {order.purchase && order.status === 'packing' && <Pressable style={styles.primary} onPress={() => router.push(`/packing/${order.id}`)}><Text style={styles.primaryText}>Open Packing List</Text></Pressable>}
    {order.status === 'ready' && !order.shipment && <Pressable style={styles.primary} onPress={() => createMockShipment(order.id, 'J&T (EasyParcel mock)')}><Text style={styles.primaryText}>Create Mock Shipment</Text></Pressable>}
    {order.status === 'ready' && order.shipment && <Pressable style={styles.primary} onPress={() => markOrderShipped(order.id, order.shipment?.courier ?? 'J&T (EasyParcel mock)')}><Text style={styles.primaryText}>Mark as Shipped</Text></Pressable>}
    {order.shipment && <View style={styles.card}><Text style={styles.section}>Shipment</Text><Text style={styles.instructions}>Courier: {order.shipment.courier}\nTracking Number: {order.shipment.trackingNumber}\nShipment Status: {order.shipment.status}</Text>{order.status === 'shipped' && order.shipment.status !== 'delivered' && <Pressable style={styles.secondary} onPress={() => syncShipmentStatus(order.id)}><Text style={styles.secondaryText}>Refresh Mock Courier Status</Text></Pressable>}{order.shipment.status === 'delivered' && <Text style={styles.success}>Delivered</Text>}</View>}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: THEME.background }, content: { width: '100%', maxWidth: 700, alignSelf: 'center', padding: SPACING['2xl'], paddingBottom: SPACING['3xl'] }, back: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, paddingVertical: SPACING.sm }, backText: { color: THEME.primary, fontWeight: '700' }, title: { color: THEME.text.primary, fontSize: FONT_SIZES['2xl'], fontWeight: '800', marginVertical: SPACING.lg }, card: { backgroundColor: THEME.surface, borderRadius: BORDER_RADIUS.lg, padding: SPACING.lg, marginBottom: SPACING.md, borderWidth: 1, borderColor: THEME.border }, image: { width: '100%', height: 220, backgroundColor: '#F3F4F6', borderRadius: BORDER_RADIUS.md }, receipt: { width: '100%', height: 180, marginVertical: SPACING.md }, productName: { color: THEME.text.primary, fontSize: FONT_SIZES.lg, fontWeight: '800', marginTop: SPACING.md }, meta: { color: THEME.text.secondary, fontSize: FONT_SIZES.sm, marginTop: SPACING.xs }, total: { color: THEME.primary, fontSize: FONT_SIZES.xl, fontWeight: '800', marginTop: SPACING.md }, section: { color: THEME.text.primary, fontSize: FONT_SIZES.lg, fontWeight: '800', marginBottom: SPACING.sm }, label: { color: THEME.text.primary, fontWeight: '700', marginTop: SPACING.lg }, status: { color: THEME.primary, fontWeight: '700', marginBottom: SPACING.md }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm, marginTop: SPACING.sm }, primary: { backgroundColor: THEME.primary, borderRadius: BORDER_RADIUS.md, padding: SPACING.md, alignItems: 'center', marginTop: SPACING.sm }, primaryText: { color: '#FFFFFF', fontWeight: '800', fontSize: FONT_SIZES.xs }, secondary: { backgroundColor: '#F5F3FF', borderRadius: BORDER_RADIUS.md, padding: SPACING.md, alignItems: 'center', marginTop: SPACING.sm }, secondaryText: { color: THEME.primary, fontWeight: '800', fontSize: FONT_SIZES.xs }, danger: { backgroundColor: '#FEE2E2', borderRadius: BORDER_RADIUS.md, padding: SPACING.md, alignItems: 'center', marginTop: SPACING.sm }, dangerText: { color: THEME.status.error, fontWeight: '800', fontSize: FONT_SIZES.xs }, customerRow: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm }, option: { borderWidth: 1, borderColor: THEME.border, borderRadius: BORDER_RADIUS.md, padding: SPACING.sm, marginTop: SPACING.sm }, selected: { borderColor: THEME.primary, backgroundColor: '#F5F3FF' }, optionText: { color: THEME.text.primary, fontWeight: '700' }, instructions: { color: THEME.text.secondary, marginVertical: SPACING.sm }, success: { color: THEME.status.success, fontWeight: '700', marginTop: SPACING.md }, error: { color: THEME.status.error, padding: SPACING['2xl'] } });
