import React, { useState } from 'react';
import { Alert, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { confirmExtraStockPurchase, confirmPurchase, FinancePaymentMethod, getOrder, getProduct, getProductVariant, uploadPurchaseReceipt, useMockDatabase } from '../../../services/mockDatabase';
import { BORDER_RADIUS, FONT_SIZES, SPACING, THEME } from '../../../theme';

export default function PurchaseFormScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>();
  const db = useMockDatabase();
  const order = id ? getOrder(id, db) : undefined;
  const item = order ? db.orderItems.find((entry) => entry.orderId === order.id) : undefined;
  const variant = item ? getProductVariant(item.productVariantId, db) : undefined;
  const product = variant ? getProduct(variant.productId, db) : undefined;
  const [classification, setClassification] = useState<'customer_order' | 'extra_stock'>('customer_order');
  const [productCost, setProductCost] = useState(product?.costPrice.toString() ?? '0');
  const [quantity, setQuantity] = useState(String(item?.quantity ?? 1));
  const [receipt, setReceipt] = useState('');
  const [paymentMethod, setPaymentMethod] = useState<FinancePaymentMethod>('cash');
  const [transport, setTransport] = useState('0');
  const [parking, setParking] = useState('0');
  const [toll, setToll] = useState('0');
  const [other, setOther] = useState('0');
  if (!order || !product || !variant) return <SafeAreaView style={styles.safe}><Text style={styles.error}>Order not found.</Text></SafeAreaView>;
  const total = [productCost, transport, parking, toll, other].reduce((sum, value) => sum + (Number(value) || 0), 0);
  const pickReceipt = async (camera: boolean) => { const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return; const result = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.9 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.9 }); if (!result.canceled) { setReceipt(result.assets[0].uri); uploadPurchaseReceipt(order.id, result.assets[0].uri); } };
  const save = () => { if (!receipt) return; const saved = confirmPurchase(order.id, { productCost: Number(productCost) || 0, transport: Number(transport) || 0, parking: Number(parking) || 0, toll: Number(toll) || 0, other: Number(other) || 0, paymentMethod, receiptUri: receipt }); if (!saved) { Alert.alert('Payment Required', 'Verify customer payment before confirming this purchase.'); return; } router.replace(`/order/${order.id}`); };
  const saveExtra = () => { confirmExtraStockPurchase({ tripId: order.tripId, productId: product.id, productVariantId: variant.id, quantity: Number(quantity) || 1, cost: Number(productCost) || 0, sellingPrice: product.sellingPrice, purchaseReceiptUri: receipt || undefined, paymentMethod }); Alert.alert('Extra Stock Saved', 'Inventory increased and Money Out recorded.'); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Confirm Purchase</Text><Text style={styles.meta}>{product.name} · Size {variant.size}</Text><View style={styles.card}><Text style={styles.section}>Classification</Text><View style={styles.actions}>{(['customer_order', 'extra_stock'] as const).map((value) => <Pressable key={value} style={[styles.option, classification === value && styles.selected]} onPress={() => setClassification(value)}><Text style={styles.optionText}>{value === 'customer_order' ? 'Customer Order' : 'Extra Stock'}</Text></Pressable>)}</View>{classification === 'extra_stock' && <Field label="Quantity" value={quantity} onChangeText={setQuantity} />}</View><View style={styles.card}>{[['Product Cost', productCost, setProductCost], ['Transport', transport, setTransport], ['Parking', parking, setParking], ['Toll', toll, setToll], ['Other Expenses', other, setOther]].map(([label, value, setter]) => <Field key={label as string} label={label as string} value={value as string} onChangeText={setter as (value: string) => void} />)}<Text style={styles.total}>Total: RM{total.toFixed(2)}</Text><Text style={styles.label}>Paid From</Text><View style={styles.actions}>{(['cash', 'bank'] as FinancePaymentMethod[]).map((value) => <Pressable key={value} style={[styles.option, paymentMethod === value && styles.selected]} onPress={() => setPaymentMethod(value)}><Text style={styles.optionText}>{value}</Text></Pressable>)}</View></View><View style={styles.card}><Text style={styles.section}>Purchase Receipt</Text>{receipt ? <View><Image source={{ uri: receipt }} style={styles.receipt} /><View style={styles.actions}><Pressable onPress={() => pickReceipt(false)}><Text style={styles.link}>Replace</Text></Pressable><Pressable onPress={() => setReceipt('')}><Text style={styles.remove}>Remove</Text></Pressable></View></View> : <View style={styles.actions}><Pressable style={styles.option} onPress={() => pickReceipt(false)}><Text style={styles.optionText}>Photo Library</Text></Pressable><Pressable style={styles.option} onPress={() => pickReceipt(true)}><Text style={styles.optionText}>Camera</Text></Pressable></View>}</View><Pressable disabled={!receipt} style={[styles.primary, !receipt && styles.disabled]} onPress={classification === 'extra_stock' ? saveExtra : save}><Text style={styles.primaryText}>{classification === 'extra_stock' ? 'Save Extra Stock' : 'Confirm Customer Order Purchase'}</Text></Pressable></ScrollView></SafeAreaView>;
}
function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} keyboardType="decimal-pad" style={styles.input} /></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: THEME.background }, content: { width: '100%', maxWidth: 680, alignSelf: 'center', padding: SPACING['2xl'], paddingBottom: SPACING['3xl'] }, title: { color: THEME.text.primary, fontSize: FONT_SIZES['2xl'], fontWeight: '800' }, meta: { color: THEME.text.secondary, marginTop: SPACING.xs, marginBottom: SPACING.lg }, card: { backgroundColor: THEME.surface, borderRadius: BORDER_RADIUS.lg, padding: SPACING.lg, marginBottom: SPACING.md, borderWidth: 1, borderColor: THEME.border }, section: { color: THEME.text.primary, fontSize: FONT_SIZES.lg, fontWeight: '800', marginBottom: SPACING.md }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: SPACING.md }, label: { color: THEME.text.primary, fontWeight: '700' }, input: { width: 120, borderWidth: 1, borderColor: THEME.border, borderRadius: BORDER_RADIUS.md, padding: SPACING.sm, textAlign: 'right', color: THEME.text.primary }, actions: { flexDirection: 'row', gap: SPACING.sm, flexWrap: 'wrap' }, option: { backgroundColor: '#F5F3FF', borderRadius: BORDER_RADIUS.md, padding: SPACING.md }, selected: { borderWidth: 2, borderColor: THEME.primary }, optionText: { color: THEME.primary, fontWeight: '800' }, total: { color: THEME.primary, fontWeight: '900', fontSize: FONT_SIZES.lg, marginBottom: SPACING.md }, receipt: { width: '100%', height: 220, marginVertical: SPACING.md }, link: { color: THEME.primary, fontWeight: '800' }, remove: { color: THEME.status.error, fontWeight: '800' }, primary: { backgroundColor: THEME.primary, borderRadius: BORDER_RADIUS.md, padding: SPACING.md, alignItems: 'center', marginTop: SPACING.sm }, disabled: { opacity: 0.45 }, primaryText: { color: '#FFFFFF', fontWeight: '800' }, error: { padding: SPACING['2xl'], color: THEME.status.error } });
